In [260]:
import pandas as pd

In [261]:
BackOrders_data = pd.read_csv("BackOrders.csv")

In [262]:
BackOrders_data.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1888279,117,NaN,0,0,0,0,0,0,15,...,0,-99.00,-99.00,0,No,No,Yes,Yes,No,No
1,1870557,7,2.0,0,0,0,0,0,0,0,...,0,0.50,0.28,0,Yes,No,No,Yes,No,No
2,1475481,258,15.0,10,10,77,184,46,132,256,...,0,0.54,0.70,0,No,No,No,Yes,No,No
3,1758220,46,2.0,0,0,0,0,1,2,6,...,0,0.75,0.90,0,Yes,No,No,Yes,No,No
4,1360312,2,2.0,0,4,6,10,2,2,5,...,0,0.97,0.92,0,No,No,No,Yes,No,No

In [263]:
target_variable = BackOrders_data['went_on_backorder']

In [264]:
type(target_variable)

pandas.core.series.Series

In [265]:
BackOrders_data = BackOrders_data.drop("sku", axis=1)

In [266]:
BackOrders_data = BackOrders_data.drop("went_on_backorder", axis=1)

In [267]:
BackOrders_data

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
0,117,NaN,0,0,0,0,0,0,15,15,...,No,0,-99.00,-99.00,0,No,No,Yes,Yes,No
1,7,2.0,0,0,0,0,0,0,0,0,...,No,0,0.50,0.28,0,Yes,No,No,Yes,No
2,258,15.0,10,10,77,184,46,132,256,365,...,No,0,0.54,0.70,0,No,No,No,Yes,No
3,46,2.0,0,0,0,0,1,2,6,9,...,No,0,0.75,0.90,0,Yes,No,No,Yes,No
4,2,2.0,0,4,6,10,2,2,5,6,...,No,0,0.97,0.92,0,No,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61584,6,8.0,0,24,24,24,0,7,9,12,...,No,0,0.98,0.98,0,No,No,No,Yes,No
61585,130,2.0,0,40,80,140,18,108,230,317,...,No,0,0.51,0.28,0,No,No,No,Yes,No
61586,135,9.0,0,0,0,0,10,40,65,89,...,No,0,1.00,0.99,0,No,No,Yes,Yes,No
61587,63,NaN,0,0,0,0,452,1715,3425,4864,...,No,0,-99.00,-99.00,1,No,No,No,No,No
61588,0,2.0,0,8,8,8,0,1,1,1,...,No,0,0.79,0.78,0,Yes,No,No,Yes,No

In [268]:
BackOrders_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61589 entries, 0 to 61588
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   national_inv       61589 non-null  int64
 1   lead_time          58186 non-null  float64
 2   in_transit_qty     61589 non-null  int64
 3   forecast_3_month   61589 non-null  int64
 4   forecast_6_month   61589 non-null  int64
 5   forecast_9_month   61589 non-null  int64
 6   sales_1_month      61589 non-null  int64
 7   sales_3_month      61589 non-null  int64
 8   sales_6_month      61589 non-null  int64
 9   sales_9_month      61589 non-null  int64
 10  min_bank           61589 non-null  int64
 11  potential_issue    61589 non-null  object
 12  pieces_past_due    61589 non-null  int64
 13  perf_6_month_avg   61589 non-null  float64
 14  perf_12_month_avg  61589 non-null  float64
 15  local_bo_qty       61589 non-null  int64
 16  deck_risk          61589 non-null  object
 17  oe_constraint      61589 non-null  object
 18  ppap_risk          61589 non-null  object
 19  stop_auto_buy      61589 non-null  object
 20  rev_stop           61589 non-null  object
dtypes: float64(3), int64(12), object(6)
memory usage: 9.9+ MB

In [269]:
BackOrders_data_num = BackOrders_data.select_dtypes(include=["int64", "float64"])
BackOrders_data_num_col = BackOrders_data_num.columns.tolist()

In [270]:
BackOrders_data_num

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty
0,117,NaN,0,0,0,0,0,0,15,15,1,0,-99.00,-99.00,0
1,7,2.0,0,0,0,0,0,0,0,0,0,0,0.50,0.28,0
2,258,15.0,10,10,77,184,46,132,256,365,47,0,0.54,0.70,0
3,46,2.0,0,0,0,0,1,2,6,9,1,0,0.75,0.90,0
4,2,2.0,0,4,6,10,2,2,5,6,0,0,0.97,0.92,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61584,6,8.0,0,24,24,24,0,7,9,12,1,0,0.98,0.98,0
61585,130,2.0,0,40,80,140,18,108,230,317,34,0,0.51,0.28,0
61586,135,9.0,0,0,0,0,10,40,65,89,2,0,1.00,0.99,0
61587,63,NaN,0,0,0,0,452,1715,3425,4864,542,0,-99.00,-99.00,1
61588,0,2.0,0,8,8,8,0,1,1,1,0,0,0.79,0.78,0

In [271]:
BackOrders_data_cat = BackOrders_data.select_dtypes(include=["object"]).copy()

In [272]:
BackOrders_data_cat

      potential_issue deck_risk oe_constraint ppap_risk stop_auto_buy rev_stop
0                  No        No            No       Yes           Yes       No
1                  No       Yes            No        No           Yes       No
2                  No        No            No        No           Yes       No
3                  No       Yes            No        No           Yes       No
4                  No        No            No        No           Yes       No
...               ...       ...           ...       ...           ...      ...
61584              No        No            No        No           Yes       No
61585              No        No            No        No           Yes       No
61586              No        No            No       Yes           Yes       No
61587              No        No            No        No            No       No
61588              No       Yes            No        No           Yes       No

[61589 rows x 6 columns]

In [273]:
def show_missing(data):
    return data.columns[data.isnull().any()].tolist()

missing_num_col = show_missing(BackOrders_data_num)

In [274]:
missing_num_col

['lead_time']

In [275]:
missing_num_count = BackOrders_data_num[missing_num_col].isnull().sum()

In [276]:
missing_num_count

lead_time    3403
dtype: int64

In [277]:
BackOrders_data_num[missing_num_col].median()

lead_time    8.0
dtype: float64

In [278]:
BackOrders_data_num[missing_num_col].mean()

lead_time    7.559619
dtype: float64

In [279]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")

BackOrders_data_num_impute = imputer.fit_transform(BackOrders_data_num)

In [280]:
BackOrders_data_num_impute_df = pd.DataFrame(BackOrders_data_num_impute, columns=BackOrders_data_num_col)

In [281]:
BackOrders_data_num_impute

array([[117.  ,   8.  ,   0.  , ..., -99.  , -99.  ,   0.  ],
       [  7.  ,   2.  ,   0.  , ...,   0.5 ,   0.28,   0.  ],
       [258.  ,  15.  ,  10.  , ...,   0.54,   0.7 ,   0.  ],
       ...,
       [135.  ,   9.  ,   0.  , ...,   1.  ,   0.99,   0.  ],
       [ 63.  ,   8.  ,   0.  , ..., -99.  , -99.  ,   1.  ],
       [  0.  ,   2.  ,   0.  , ...,   0.79,   0.78,   0.  ]])

In [282]:
show_missing(BackOrders_data_num_impute_df)

[]

In [283]:
BackOrders_data_cat

      potential_issue deck_risk oe_constraint ppap_risk stop_auto_buy rev_stop
0                  No        No            No       Yes           Yes       No
1                  No       Yes            No        No           Yes       No
2                  No        No            No        No           Yes       No
3                  No       Yes            No        No           Yes       No
4                  No        No            No        No           Yes       No
...               ...       ...           ...       ...           ...      ...
61584              No        No            No        No           Yes       No
61585              No        No            No        No           Yes       No
61586              No        No            No       Yes           Yes       No
61587              No        No            No        No            No       No
61588              No       Yes            No        No           Yes       No

[61589 rows x 6 columns]

In [284]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

for col in BackOrders_data_cat.columns :
    BackOrders_data_cat[col] = encoder.fit_transform(BackOrders_data_cat[col])

In [285]:
BackOrders_data_cat.head()

,potential_issue,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
0,0,0,0,1,1,0
1,0,1,0,0,1,0
2,0,0,0,0,1,0
3,0,1,0,0,1,0
4,0,0,0,0,1,0

In [286]:
target_variable

0         No
1         No
2         No
3         No
4         No
        ...
61584     No
61585     No
61586     No
61587    Yes
61588    Yes
Name: went_on_backorder, Length: 61589, dtype: object

In [287]:
target_variable = encoder.fit_transform(target_variable).copy()
target_variable = pd.Series(target_variable)

In [288]:
target_variable

0        0
1        0
2        0
3        0
4        0
        ..
61584    0
61585    0
61586    0
61587    1
61588    1
Length: 61589, dtype: int32

In [289]:
total_data=pd.concat([BackOrders_data_num_impute_df, BackOrders_data_cat], axis=1)

In [290]:
total_data.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,potential_issue,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
0,117.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,15.0,...,0.0,-99.00,-99.00,0.0,0,0,0,1,1,0
1,7.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.50,0.28,0.0,0,1,0,0,1,0
2,258.0,15.0,10.0,10.0,77.0,184.0,46.0,132.0,256.0,365.0,...,0.0,0.54,0.70,0.0,0,0,0,0,1,0
3,46.0,2.0,0.0,0.0,0.0,0.0,1.0,2.0,6.0,9.0,...,0.0,0.75,0.90,0.0,0,1,0,0,1,0
4,2.0,2.0,0.0,4.0,6.0,10.0,2.0,2.0,5.0,6.0,...,0.0,0.97,0.92,0.0,0,0,0,0,1,0

In [291]:
total_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61589 entries, 0 to 61588
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   national_inv       61589 non-null  float64
 1   lead_time          61589 non-null  float64
 2   in_transit_qty     61589 non-null  float64
 3   forecast_3_month   61589 non-null  float64
 4   forecast_6_month   61589 non-null  float64
 5   forecast_9_month   61589 non-null  float64
 6   sales_1_month      61589 non-null  float64
 7   sales_3_month      61589 non-null  float64
 8   sales_6_month      61589 non-null  float64
 9   sales_9_month      61589 non-null  float64
 10  min_bank           61589 non-null  float64
 11  pieces_past_due    61589 non-null  float64
 12  perf_6_month_avg   61589 non-null  float64
 13  perf_12_month_avg  61589 non-null  float64
 14  local_bo_qty       61589 non-null  float64
 15  potential_issue    61589 non-null  int32
 16  deck_risk          61589 non-null  int32
 17  oe_constraint      61589 non-null  int32
 18  ppap_risk          61589 non-null  int32
 19  stop_auto_buy      61589 non-null  int32
 20  rev_stop           61589 non-null  int32
dtypes: float64(15), int32(6)
memory usage: 8.5 MB

In [292]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(total_data, target_variable, test_size=0.25, random_state=42)

In [293]:
total_data.shape

(61589, 21)

In [294]:
show_missing(x_train)

[]

In [295]:
x_train.shape

(46191, 21)

In [296]:
type(y_train)

pandas.core.series.Series

In [297]:
x_test.shape

(15398, 21)

In [298]:
61589*0.25

15397.25

In [299]:
x_train

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,...,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,potential_issue,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
45537,8.0,8.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,10.0,...,0.0,0.78,0.83,0.0,0,1,0,0,1,0
34224,18.0,3.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,4.0,...,0.0,0.98,0.98,0.0,0,0,0,0,1,0
46945,12.0,8.0,8.0,5.0,15.0,25.0,7.0,22.0,36.0,55.0,...,0.0,0.85,0.80,0.0,0,0,0,0,1,0
5994,7.0,12.0,0.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.48,0.48,0.0,0,1,0,0,1,0
18143,9.0,2.0,0.0,35.0,63.0,77.0,10.0,26.0,36.0,86.0,...,0.0,0.97,0.93,0.0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54343,0.0,2.0,0.0,2.0,2.0,3.0,1.0,2.0,2.0,3.0,...,0.0,0.98,0.95,0.0,0,0,0,0,1,0
38158,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.68,0.64,0.0,0,0,0,0,1,0
860,45.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.73,0.76,0.0,0,1,0,0,1,0
15795,2.0,2.0,0.0,6.0,12.0,16.0,2.0,6.0,10.0,13.0,...,0.0,0.95,0.95,0.0,0,0,0,0,1,0
56422,19.0,8.0,0.0,30.0,75.0,90.0,3.0,16.0,44.0,107.0,...,0.0,0.98,0.98,0.0,0,0,0,1,1,0

In [300]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(random_state=42)

rfe_RF=RFE(RF,n_features_to_select=3,verbose=21)

rfe_RF.fit(x_train, y_train)
names=x_train.columns.tolist()
b=rfe_RF.ranking_

a=pd.DataFrame(sorted(list(map(lambda x,y: (x,y),b,names))),columns=['rank','features'])
a.to_csv('feature_selection.csv')

RFE_selected=a['features'][a['rank']==1]

Fitting estimator with 21 features.
Fitting estimator with 20 features.
Fitting estimator with 19 features.
Fitting estimator with 18 features.
Fitting estimator with 17 features.
Fitting estimator with 16 features.
Fitting estimator with 15 features.
Fitting estimator with 14 features.
Fitting estimator with 13 features.
Fitting estimator with 12 features.
Fitting estimator with 11 features.
Fitting estimator with 10 features.
Fitting estimator with 9 features.
Fitting estimator with 8 features.
Fitting estimator with 7 features.
Fitting estimator with 6 features.
Fitting estimator with 5 features.
Fitting estimator with 4 features.

In [301]:
RFE_selected

0    forecast_3_month
1        national_inv
2       sales_9_month
Name: features, dtype: object

In [302]:
x_train=x_train[RFE_selected]
x_test=x_test[RFE_selected]

In [303]:
x_train.head()

       forecast_3_month  national_inv  sales_9_month
45537               0.0           8.0           10.0
34224               0.0          18.0            4.0
46945               5.0          12.0           55.0
5994                2.0           7.0            0.0
18143              35.0           9.0           86.0

In [304]:
from sklearn.ensemble import RandomForestClassifier
RF_model=RandomForestClassifier(max_depth=3, max_features=0.6, min_samples_leaf=4,n_estimators=9)
RF_model.fit(x_train,y_train)

RandomForestClassifier(max_depth=3, max_features=0.6, min_samples_leaf=4,
                       n_estimators=9)

In [305]:
pred=RF_model.predict(x_test)

In [306]:
out_data=pd.DataFrame({'true':y_test,'model_predicted':pred})
out_data.to_csv('BackOrders_Prediction_Analysis.csv')

In [307]:
preds=RF_model.predict(x_test)

In [308]:
from sklearn.metrics import accuracy_score
accuracy_test=accuracy_score(y_test, preds)
accuracy_test

0.8761527471100143

In [309]:
from sklearn.model_selection import GridSearchCV

In [310]:
param_grid = {"n_estimators" : [100, 200, 300],
              "max_depth" : [3, 6],
              "min_samples_leaf" : [2, 4],
              "max_features" : [0.4,0.5]
             }

RF_model=RandomForestClassifier()
clf = GridSearchCV(RF_model, param_grid, cv=3)
clf.fit(x_train,y_train)
clf.best_estimator_

RandomForestClassifier(max_depth=6, max_features=0.4, min_samples_leaf=4,
                       n_estimators=300)

In [311]:
preds=clf.best_estimator_.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_test=accuracy_score(y_test, preds)

In [312]:
accuracy_test

0.8944018703727756

In [313]:
import pickle as pk

my_first_out=open('my_first_pickle_file_withRFE_RF_batch_2.pickle','wb')

pk.dump(clf.best_estimator_,my_first_out)

my_first_out.close()

In [314]:
RF_model.fit(x_train,y_train)
pred_probability=RF_model.predict_proba(x_test)

from sklearn.metrics import accuracy_score
accuracy_test=accuracy_score(y_test, preds)

train_preds=RF_model.predict(x_train)

accuracy_train=accuracy_score(y_train, train_preds)

from sklearn.metrics import classification_report
target_names = ['Successful', 'Not Successful']
print(classification_report(y_test, preds, target_names=target_names))

                precision    recall  f1-score   support

    Successful       0.92      0.95      0.94     12597
Not Successful       0.75      0.62      0.68      2801

      accuracy                           0.89     15398
     macro avg       0.84      0.79      0.81     15398
  weighted avg       0.89      0.89      0.89     15398